//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class activityLog
    {
        public long LogId { get; set; }
        public Nullable<long> ActivityId { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string ActivityType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> AssignedTo { get; set; }
        public string ExportTest { get; set; }
    }
}
