//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> ActivityTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> RemindDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string DueTime { get; set; }
        public string RemindTime { get; set; }
        public Nullable<bool> NotificationFlag { get; set; }
        public string Notes { get; set; }
    }
}
