//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class appliEducation_stage
    {
        public Nullable<decimal> userId { get; set; }
        public Nullable<decimal> number { get; set; }
        public string lavel { get; set; }
        public string institution { get; set; }
        public string location { get; set; }
        public string degreeEarned { get; set; }
        public string major { get; set; }
        public string degreeYear { get; set; }
        public Nullable<decimal> gpa { get; set; }
        public string gpaInMajor { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string Country { get; set; }
        public string degreeYearTo { get; set; }
        public string Graduated { get; set; }
        public int appliEducationID { get; set; }
    }
}
