//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignWorkOrder
    {
        public int AWId { get; set; }
        public int UserID { get; set; }
        public int WorkOrderID { get; set; }
        public int AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string assignmentId { get; set; }
        public string assignmentBY { get; set; }
        public string policyid { get; set; }
        public string policy_status { get; set; }
        public Nullable<decimal> ApplicantRating { get; set; }
    }
}
