//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateInOutT
    {
        public int InOutID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string AssociateName { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PunchType { get; set; }
        public string In_Out { get; set; }
        public string DeptID { get; set; }
        public string JobID { get; set; }
        public string ProjectID { get; set; }
        public string ModuleID { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> NormalIn { get; set; }
        public Nullable<System.DateTime> NormalOut { get; set; }
        public Nullable<System.DateTime> LunchIn { get; set; }
        public Nullable<System.DateTime> LunchOut { get; set; }
        public Nullable<System.DateTime> breakIn { get; set; }
        public Nullable<System.DateTime> breakOut { get; set; }
        public Nullable<decimal> NonBillableTime { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public string InOutDay { get; set; }
        public string status { get; set; }
        public Nullable<decimal> modifiedBy { get; set; }
        public string imageStatus { get; set; }
        public string assignmentId { get; set; }
        public string weeklyNote { get; set; }
        public Nullable<bool> OverTime { get; set; }
        public string timesheetType { get; set; }
        public Nullable<decimal> REG_Hrs { get; set; }
        public Nullable<decimal> OT_Hrs { get; set; }
        public Nullable<decimal> DT_Hrs { get; set; }
        public string PayrollDesc_Regular { get; set; }
        public string PayrollDesc_OT { get; set; }
        public string PayrollDesc_DT { get; set; }
        public string ServiceItem { get; set; }
        public string NonBillableHour { get; set; }
    }
}
