//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEventRequest
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string Time1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string Time2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public string Time3 { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public Nullable<int> Venture { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
