//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidateCompetency_Parsed
    {
        public long competencyId { get; set; }
        public long resumeId { get; set; }
        public string Name { get; set; }
        public string description { get; set; }
        public string CompetencyEvidence_Type { get; set; }
        public Nullable<int> UserArea_CummulativeMonth { get; set; }
        public Nullable<System.DateTime> lastUsedDate { get; set; }
        public string skillLevel { get; set; }
    
        public virtual Resume_Parsed Resume_Parsed { get; set; }
    }
}
