//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidateAddress_Parsed
    {
        public long candidateAddressId { get; set; }
        public string addressType { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string Muncipality { get; set; }
        public string Region { get; set; }
        public string CountryCode { get; set; }
        public string postalcode { get; set; }
        public long ResumeId { get; set; }
    
        public virtual Resume_Parsed Resume_Parsed { get; set; }
    }
}
