//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidateWorkReference
    {
        public decimal id { get; set; }
        public Nullable<decimal> userId { get; set; }
        public string number { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string middleInitial { get; set; }
        public string lastName { get; set; }
        public string company { get; set; }
        public Nullable<decimal> lengthOfJob { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<bool> mayWeContact { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string email { get; set; }
        public Nullable<decimal> resumeID { get; set; }
        public string relationship { get; set; }
        public string Graduated { get; set; }
        public string CompanyName { get; set; }
    }
}
