//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidateSchool_Parsed
    {
        public long candidateschoolId { get; set; }
        public long resumeId { get; set; }
        public string schoolName { get; set; }
        public string degreeName { get; set; }
        public string degreeMajor { get; set; }
        public string DegreeMinor { get; set; }
        public Nullable<decimal> userArea_NormalizedGPA { get; set; }
        public string DegreeDate { get; set; }
        public string DegreeStartDate { get; set; }
        public string DegreeEndDate { get; set; }
        public string schoolCity { get; set; }
        public string schoolstate { get; set; }
        public string country { get; set; }
        public string schoolPinCode { get; set; }
    
        public virtual Resume_Parsed Resume_Parsed { get; set; }
    }
}
