//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidateAchivement_Parsed
    {
        public long candidateAchivement_Parsed1 { get; set; }
        public long resumeId { get; set; }
        public string date { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string IssuingAuthority { get; set; }
        public string IssuingAuthorityPlace { get; set; }
        public string EffectiveDate_ValidFrom { get; set; }
        public string EffectiveDate_ValidTo { get; set; }
        public string EffectiveDate_FirstIssuedDate { get; set; }
    
        public virtual Resume_Parsed Resume_Parsed { get; set; }
    }
}
