//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidateReference_Parsed
    {
        public long candidateReferenceId { get; set; }
        public Nullable<long> resumeId { get; set; }
        public string PositionTitle { get; set; }
        public string PersonName { get; set; }
        public string Comment { get; set; }
        public string PhoneNumber { get; set; }
        public string RefEmailAddress { get; set; }
        public string CompanyName { get; set; }
        public string address { get; set; }
    
        public virtual Resume_Parsed Resume_Parsed { get; set; }
    }
}
