//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationInfo
    {
        public decimal Id { get; set; }
        public string CertificationType { get; set; }
        public Nullable<System.DateTime> CertificationDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> userId { get; set; }
        public Nullable<decimal> resumeId { get; set; }
        public string LicenseNumber { get; set; }
        public string state { get; set; }
        public Nullable<long> Temp_UserID { get; set; }
    }
}
