//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public long ClientNumber { get; set; }
        public string ClientID { get; set; }
        public byte[] ConnectionString { get; set; }
        public string ServerName { get; set; }
        public string CompanyName { get; set; }
        public string Country { get; set; }
        public string Timesheet_Type { get; set; }
        public string Timesheet { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string companyphone { get; set; }
        public string fax { get; set; }
        public string companywebsite { get; set; }
        public string companylogo { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string companytype { get; set; }
        public Nullable<System.DateTime> expirydate { get; set; }
        public Nullable<bool> active { get; set; }
        public string site_type { get; set; }
        public string AttachmentUrl { get; set; }
    }
}
