//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRegistration
    {
        public int ClientRegistrationId { get; set; }
        public string CompanyName { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip { get; set; }
        public string RefrredBy { get; set; }
        public string OtherReferral { get; set; }
        public string BillingContactName { get; set; }
        public string BillingPhnNo { get; set; }
        public string BillingEmail { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingCountry { get; set; }
        public string BillingZip { get; set; }
        public string PosTitle { get; set; }
        public string PosType { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> HourlyWage { get; set; }
        public string Schedule { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string PosDetail { get; set; }
        public string SupervisorName { get; set; }
        public string SupervisorphNo { get; set; }
        public string SuperVisorEmail { get; set; }
        public string BudgetCode { get; set; }
        public string UNSPSCCode { get; set; }
        public Nullable<bool> IsConvert { get; set; }
        public string salary { get; set; }
        public Nullable<decimal> FeePercentage { get; set; }
        public Nullable<decimal> FeeAmt { get; set; }
        public Nullable<System.DateTime> GDate { get; set; }
        public string GNote { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
    }
}
