//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClockData
    {
        public int Counter { get; set; }
        public string PunchType { get; set; }
        public string BadgeID { get; set; }
        public string PlacementID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string StartLocationNo { get; set; }
        public Nullable<byte> StartLocationType { get; set; }
        public string EndLocationNo { get; set; }
        public Nullable<byte> EndLocationType { get; set; }
        public string CompanyCode { get; set; }
        public bool isUpdated { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string PunchAddress { get; set; }
    }
}
