//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsentForm
    {
        public int ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ResumeID { get; set; }
        public Nullable<long> Temp_UserID { get; set; }
        public string FormName { get; set; }
        public string LocationReceivedTraining { get; set; }
        public string TrainingDate { get; set; }
        public string VaccineName { get; set; }
        public string ChickenPox { get; set; }
        public Nullable<bool> CopyRecord { get; set; }
        public string VaccinationName { get; set; }
    }
}
