//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_Value_Master
    {
        public long CValueId { get; set; }
        public long UserID { get; set; }
        public string Module { get; set; }
        public Nullable<long> ModuleRecordId { get; set; }
        public Nullable<long> ModuleRecordIdTmp { get; set; }
        public Nullable<long> MasterFieldId { get; set; }
        public string CustomFieldvalue { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string SearchIndex { get; set; }
    }
}
