//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_DrpChkValues
    {
        public long DrpValueId { get; set; }
        public long FieldId { get; set; }
        public string DrpValue { get; set; }
        public bool IsDefault { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
