//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_DbError
    {
        public long ErrorId { get; set; }
        public string ErrorNo { get; set; }
        public string ErrorSeverity { get; set; }
        public string ErrorState { get; set; }
        public string ErrorLine { get; set; }
        public string ProcedureName { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
