//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dynamic_Fields
    {
        public long Field_ID { get; set; }
        public string Table_Name { get; set; }
        public string Module_Name { get; set; }
        public string Field_Name { get; set; }
        public string System_Label { get; set; }
        public int System_Order { get; set; }
        public string Field_Label { get; set; }
        public string Field_Description { get; set; }
        public string Field_ToolTip { get; set; }
        public long ControlID { get; set; }
        public string DataType { get; set; }
        public string InputDataType { get; set; }
        public int MaxLength { get; set; }
        public bool SystemDisplay { get; set; }
        public Nullable<long> ValidationType { get; set; }
        public string DefaultValue { get; set; }
        public bool Display { get; set; }
        public Nullable<long> UserColSeq { get; set; }
        public Nullable<long> TableColSeq { get; set; }
        public Nullable<long> WebRowNo { get; set; }
        public Nullable<long> WebColNo { get; set; }
        public string XMLAlias { get; set; }
        public string SystemFlag { get; set; }
        public Nullable<bool> ApplicableFromWeb { get; set; }
        public string SectionNo { get; set; }
        public string SectionName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public long CutomFieldId { get; set; }
    }
}
