//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dynamic_Sections
    {
        public long SectionNo { get; set; }
        public string SectionName { get; set; }
        public string SectionType { get; set; }
        public string SectionDescription { get; set; }
        public int Repeat { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
