//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_ListMaster
    {
        public long ListMasterID { get; set; }
        public string UserID { get; set; }
        public string ListName { get; set; }
        public string ListDesc { get; set; }
        public long TotalCount { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> IsSFList { get; set; }
        public long TotalCountActive { get; set; }
        public long TotalCountActiveConfirm { get; set; }
    }
}
