//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_UploadVideo
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public string VideoShowName { get; set; }
        public string VideoShowDescription { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<bool> IsSkip { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Extension { get; set; }
        public string FileType { get; set; }
    }
}
