//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_ContactActivity
    {
        public long ActivityId { get; set; }
        public string ParentId { get; set; }
        public string UserId { get; set; }
        public int ActionID { get; set; }
        public Nullable<int> ResultId { get; set; }
        public Nullable<int> ErrorResultId { get; set; }
        public int NoOfRows { get; set; }
        public Nullable<int> NoOfRowsError { get; set; }
        public string ErrorMsg { get; set; }
        public string ActionData { get; set; }
        public string ActionSuccessData { get; set; }
        public string ActionErrorData { get; set; }
        public string InCompleteStage { get; set; }
        public string ListName { get; set; }
        public string UploadedFileName { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartRunDate { get; set; }
        public Nullable<System.DateTime> EndRunDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
