//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_SurveyQuesSet
    {
        public string QuesId { get; set; }
        public string SurveyId { get; set; }
        public string UserId { get; set; }
        public string Questions { get; set; }
        public int QTypeId { get; set; }
        public string Text { get; set; }
        public Nullable<bool> IsOtherOpRq { get; set; }
        public string OtherChoice { get; set; }
        public Nullable<bool> IsQReq { get; set; }
        public string RqErrMsg { get; set; }
        public string CBSizeSOrP { get; set; }
        public Nullable<int> QPosition { get; set; }
        public Nullable<bool> IsPageBreak { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public byte[] SubmittedDate { get; set; }
        public Nullable<int> MaxMarks { get; set; }
    }
}
