//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_SurveyAnsPattern
    {
        public long SurveyAnsPatternId { get; set; }
        public string QuesId { get; set; }
        public string UserId { get; set; }
        public string SurveyId { get; set; }
        public string Answers { get; set; }
        public string Logo { get; set; }
        public string CItemAns { get; set; }
        public string CLogo { get; set; }
        public string RowOrCol { get; set; }
        public Nullable<int> RNum { get; set; }
        public Nullable<int> CNum { get; set; }
        public string SubCItemAns { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public byte[] SubmittedDate { get; set; }
        public Nullable<bool> correctans { get; set; }
    }
}
