//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_JobMaster
    {
        public long JobMasterID { get; set; }
        public string ParentID { get; set; }
        public string UserID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string Seprator { get; set; }
        public Nullable<System.DateTime> QueueDateTime { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public int JobStatusID { get; set; }
        public bool Active { get; set; }
        public string FieldMaping { get; set; }
        public string ListID { get; set; }
        public Nullable<bool> IncludeHeader { get; set; }
        public bool InsertAction { get; set; }
        public bool UpdateAction { get; set; }
        public string ActualFileName { get; set; }
        public string JobDesc { get; set; }
        public Nullable<bool> IsLaunched { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<bool> SendNow { get; set; }
        public Nullable<long> ContactActvityId { get; set; }
        public string FromIP { get; set; }
        public int FromUpdate { get; set; }
    }
}
