//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_Company
    {
        public string CID { get; set; }
        public string CompName { get; set; }
        public string WebSite { get; set; }
        public string Phone { get; set; }
        public string CAddress { get; set; }
        public string AddedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime Addedon { get; set; }
        public string Fax { get; set; }
        public string Sector { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
    }
}
