//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_Subscriber_Events
    {
        public long EventId { get; set; }
        public long ActivityId { get; set; }
        public int resultId { get; set; }
        public string UserId { get; set; }
        public string ListMasterId { get; set; }
        public string FromIP { get; set; }
        public string Msg { get; set; }
        public string ActionData { get; set; }
        public Nullable<int> NoOfRows { get; set; }
        public bool IsError { get; set; }
        public int status { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
