//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_subscriber_list_actions
    {
        public int id { get; set; }
        public string action_short { get; set; }
        public string action_long { get; set; }
        public bool file_upload { get; set; }
    }
}
