//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_ClientRegistration
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmailId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public string PhoneNo { get; set; }
        public string TimeZoneValue { get; set; }
        public string TimeZone { get; set; }
        public string AccountType { get; set; }
        public Nullable<bool> IsUpdateEmails { get; set; }
        public string UserType { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string ViewCount { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string Language { get; set; }
        public string CompanyId { get; set; }
    }
}
