//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_Survey
    {
        public string SurveyId { get; set; }
        public string SurveyType { get; set; }
        public string SurveyName { get; set; }
        public string SurveyLogo { get; set; }
        public string UserId { get; set; }
        public Nullable<long> SampleId { get; set; }
        public string Background { get; set; }
        public string TitleText { get; set; }
        public string TitleSize { get; set; }
        public string Titlecolor { get; set; }
        public string QText { get; set; }
        public string QSize { get; set; }
        public string QColor { get; set; }
        public string AText { get; set; }
        public string ASize { get; set; }
        public string AColor { get; set; }
        public Nullable<bool> Numbering { get; set; }
        public string QSeprator { get; set; }
        public Nullable<bool> IsGreetingPage { get; set; }
        public Nullable<bool> IsSameBgcolor { get; set; }
        public string GreetingText { get; set; }
        public string GreetingLogo { get; set; }
        public string IsClosingPage { get; set; }
        public Nullable<bool> IsCSameBgcolor { get; set; }
        public string ClosingText { get; set; }
        public string ClosingLogo { get; set; }
        public string ClosingUrl { get; set; }
        public Nullable<bool> IsMulltipleResponse { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LiveDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<bool> IsUserClicked { get; set; }
        public string SurveyUrl { get; set; }
        public string SurveyUrlPrev { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsCopy { get; set; }
        public Nullable<bool> IsSaveIp { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string ScccMsg { get; set; }
        public Nullable<decimal> PassingPer { get; set; }
        public Nullable<bool> IsSubmitDocChecked { get; set; }
    }
}
