//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_SurveyPhotoMast
    {
        public string PhotoId { get; set; }
        public string UserId { get; set; }
        public string SurveyId { get; set; }
        public string Image { get; set; }
        public string ImgDesc { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
