//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_SurveyResponseEntry
    {
        public long ResponseId { get; set; }
        public string UserId { get; set; }
        public string SurveyId { get; set; }
        public string CollectorId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
        public string ResponseType { get; set; }
        public string IpAddress { get; set; }
        public string CustomValue { get; set; }
        public Nullable<long> ContactId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
