//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_SurveySend
    {
        public long id { get; set; }
        public string SurveyId { get; set; }
        public Nullable<int> SendCount { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    }
}
