//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_SurveyWelcome
    {
        public long Id { get; set; }
        public string SurveyId { get; set; }
        public int WelcomeType { get; set; }
        public string sMessage { get; set; }
        public string Logo { get; set; }
        public string BackColor { get; set; }
        public bool IsBackColorSameAsSurvey { get; set; }
        public System.DateTime Addedon { get; set; }
    }
}
