//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elearning_ManageContactFields
    {
        public long FieldId { get; set; }
        public string ParentID { get; set; }
        public string UserID { get; set; }
        public int Column_Id { get; set; }
        public string ActualColumnName { get; set; }
        public string Column_Label { get; set; }
        public string Column_Type { get; set; }
        public string Field_Type { get; set; }
        public string Description { get; set; }
        public string HoverText { get; set; }
        public string InputDataType { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<int> DisplayPosition { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public Nullable<bool> RequiredField { get; set; }
        public Nullable<bool> MultiValued { get; set; }
        public string ColumnDrpChkValues { get; set; }
    }
}
