//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_Log
    {
        public int ErrorId { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorPage { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
