//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDetail
    {
        public int Id { get; set; }
        public Nullable<long> MeetingId { get; set; }
        public Nullable<long> MentorId { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> IsDenied { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
