//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenerateXML_Log
    {
        public int Id { get; set; }
        public string JobId { get; set; }
        public string FeedType { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
    }
}
