//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardClockEmployee
    {
        public int Id { get; set; }
        public string DeviceType { get; set; }
        public string DeviceIP { get; set; }
        public string BadgeID { get; set; }
        public string DepartmentID { get; set; }
        public string JobID { get; set; }
        public string Level4ID { get; set; }
        public string Level5ID { get; set; }
        public string CompanyCode { get; set; }
    }
}
