//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRInfo
    {
        public int hrInfoId { get; set; }
        public Nullable<bool> resume { get; set; }
        public Nullable<bool> stateTaxForm { get; set; }
        public Nullable<bool> w4 { get; set; }
        public Nullable<bool> i9 { get; set; }
        public Nullable<bool> directdeposit { get; set; }
        public Nullable<bool> associateAssignAgrement { get; set; }
        public Nullable<bool> hssCodeOfCunduct { get; set; }
        public Nullable<bool> associateAssignDesc { get; set; }
        public Nullable<bool> healthBenifits { get; set; }
        public Nullable<bool> backgroundChk { get; set; }
        public Nullable<bool> drugtest { get; set; }
        public Nullable<System.DateTime> resumeUpdateDate { get; set; }
        public string pathuploaded { get; set; }
        public Nullable<decimal> userid { get; set; }
        public Nullable<bool> confidentialty { get; set; }
        public Nullable<bool> clientRequirement { get; set; }
        public Nullable<bool> CandidateRegiPlaceForm { get; set; }
        public Nullable<bool> BackGroundChkAuth { get; set; }
        public Nullable<bool> WHMISTesting { get; set; }
        public Nullable<bool> PickerPackerTest { get; set; }
        public Nullable<bool> PDAForm { get; set; }
    }
}
