//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportantDocumentRead
    {
        public long ReadId { get; set; }
        public long UserId { get; set; }
        public long DocId { get; set; }
        public string Module { get; set; }
        public System.DateTime ReadDate { get; set; }
    }
}
