//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobOrder
    {
        public decimal jobId { get; set; }
        public string jobTitle { get; set; }
        public Nullable<System.DateTime> submissionDate { get; set; }
        public string jobdescription { get; set; }
        public string educationExp { get; set; }
        public string requiredSkillLevel { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string minEducation { get; set; }
        public string payRate { get; set; }
        public string otherBenefits { get; set; }
        public Nullable<decimal> noCandidatesRequired { get; set; }
        public Nullable<decimal> branchId { get; set; }
        public string jobType { get; set; }
        public string jobCategoryId { get; set; }
        public string jobOrderStatus { get; set; }
        public string comment { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<decimal> createdBy { get; set; }
        public Nullable<decimal> modifiedBy { get; set; }
        public Nullable<decimal> requisitionId { get; set; }
        public string location { get; set; }
        public Nullable<bool> ynActive { get; set; }
    }
}
