//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class joinNowRegistration
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<bool> isDrivingLic { get; set; }
        public Nullable<bool> haveCar { get; set; }
        public Nullable<bool> asAdriver { get; set; }
        public Nullable<bool> haveConvictedCrime { get; set; }
        public string ConvictedCrimeDetails { get; set; }
        public Nullable<bool> havePassDrugTest { get; set; }
        public string AvailabilityOfWorking { get; set; }
        public Nullable<bool> isTemporaryEmp { get; set; }
        public Nullable<bool> haveScheduleRestriction { get; set; }
        public string ScheduleRestrictionDetail { get; set; }
        public string DrivingPoint { get; set; }
    }
}
