//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class joinNowApplicantData
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string referralSources { get; set; }
        public string Gender { get; set; }
        public string RaceEthnicity { get; set; }
        public string PhysicalCondition { get; set; }
        public string VeteranUSMilitary { get; set; }
        public Nullable<bool> isActiveNationalGuardReservist { get; set; }
        public Nullable<bool> RefuseToCompleteCOMPLETE { get; set; }
        public string OtherReferralDescription { get; set; }
    }
}
