//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mailing_Reports
    {
        public int Id { get; set; }
        public string BadgeId { get; set; }
        public System.DateTime Date { get; set; }
        public string EmpType { get; set; }
        public string MailType { get; set; }
        public string Status { get; set; }
        public string CompanyCode { get; set; }
    }
}
