//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MentorDetail
    {
        public long MentorDetailsId { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string NickName { get; set; }
        public string Organization { get; set; }
        public string Title { get; set; }
        public string Street1 { get; set; }
        public string AddressLine1 { get; set; }
        public string City1 { get; set; }
        public string StateProvinceRegion1 { get; set; }
        public string ZIP1 { get; set; }
        public string Country1 { get; set; }
        public string Street2 { get; set; }
        public string AddressLine2 { get; set; }
        public string City2 { get; set; }
        public string StateProvinceRegion2 { get; set; }
        public string ZIP2 { get; set; }
        public string Country2 { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public string SkypeAddress { get; set; }
        public string TwitterAddress { get; set; }
        public string LinkedIn { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public string PublicProfile { get; set; }
        public string Resume { get; set; }
        public Nullable<bool> QuestionStat { get; set; }
        public Nullable<long> MentorId { get; set; }
    }
}
