//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mentor
    {
        public long MentorId { get; set; }
        public Nullable<long> VentureId { get; set; }
        public string Name { get; set; }
        public Nullable<int> MentorTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> HaverelevantExp { get; set; }
        public Nullable<bool> WillhelpifNeeded { get; set; }
        public Nullable<bool> Recruited { get; set; }
        public Nullable<bool> Interested { get; set; }
        public Nullable<bool> Conflict_FinancialInterest { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Email { get; set; }
        public Nullable<int> VmsStatus { get; set; }
    }
}
