//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MentorQuestionary
    {
        public long MentorQuestionaryId { get; set; }
        public string Startups { get; set; }
        public string BusinessModel { get; set; }
        public string Funding { get; set; }
        public string Others1 { get; set; }
        public string Software { get; set; }
        public string LifeSciences { get; set; }
        public string IndustryOther { get; set; }
        public string Others2 { get; set; }
        public string FunctionalAreas { get; set; }
        public string Others3 { get; set; }
        public Nullable<long> MentorId { get; set; }
    }
}
