//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MileageLog
    {
        public decimal id { get; set; }
        public string description { get; set; }
        public Nullable<decimal> miles { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string userId { get; set; }
        public string assignmentId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string weekDay { get; set; }
        public string status { get; set; }
        public string imageStatus { get; set; }
        public string modifiedBy { get; set; }
        public string reportingOffice { get; set; }
    }
}
