//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleType
    {
        public int ID { get; set; }
        public string AccountTypeName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
