//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollHistory
    {
        public int PayId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string PayRate { get; set; }
    }
}
