//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int PId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OverallScore { get; set; }
        public string Comment { get; set; }
        public string Documents { get; set; }
    }
}
