//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTOApplicantPlanHistory
    {
        public int ID { get; set; }
        public int PTOApplicantID { get; set; }
        public int PTOPlanLeaveTypeID { get; set; }
        public double MaxTime { get; set; }
        public double WorkedTowardsPTO { get; set; }
        public double Earned { get; set; }
        public double CarryForward { get; set; }
        public double TimeTaken { get; set; }
        public double Balance { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
