//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTOApplicant
    {
        public PTOApplicant()
        {
            this.PTOApplicantPlans = new HashSet<PTOApplicantPlan>();
        }
    
        public int ID { get; set; }
        public decimal UserID { get; set; }
        public int PTOPlanID { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<System.DateTime> BenifitDate { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public string AssignmentID { get; set; }
    
        public virtual ICollection<PTOApplicantPlan> PTOApplicantPlans { get; set; }
    }
}
