//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportQuery
    {
        public int ID { get; set; }
        public string Query { get; set; }
        public string Name { get; set; }
        public string ReOrder { get; set; }
        public string Headers { get; set; }
        public string ReportHeader { get; set; }
        public string Hleft { get; set; }
        public string Hright { get; set; }
        public string Fleft { get; set; }
        public string Fright { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Filters { get; set; }
    }
}
