//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume_Parsed
    {
        public Resume_Parsed()
        {
            this.candidateAchivement_Parsed = new HashSet<candidateAchivement_Parsed>();
            this.candidateAddress_Parsed = new HashSet<candidateAddress_Parsed>();
            this.candidateCompetency_Parsed = new HashSet<candidateCompetency_Parsed>();
            this.candidateEmploymentHistroy_Parsed = new HashSet<candidateEmploymentHistroy_Parsed>();
            this.candidateReference_Parsed = new HashSet<candidateReference_Parsed>();
            this.candidateSchool_Parsed = new HashSet<candidateSchool_Parsed>();
        }
    
        public long ResumeId { get; set; }
        public string GivenName { get; set; }
        public string MiddleName { get; set; }
        public string FamilyName { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string CurrentOrganization { get; set; }
        public string PositionType { get; set; }
        public string PositionTitle { get; set; }
        public string StructuredXMLResume_ExecutiveSummary { get; set; }
        public string StructuredXMLResume_Objective { get; set; }
        public string StructuredXMLResume_Qualifications_QualificationSummary { get; set; }
        public string StructuredXMLResume_Comments { get; set; }
        public string StructuredXMLResume_RevisionDate { get; set; }
        public string NonXMLResume_TextResume { get; set; }
        public string Denormalized_CurrentEmployerName { get; set; }
        public string Denormalized_CurrentJobTitle { get; set; }
        public Nullable<int> UserArea_TotalMonthsExperience { get; set; }
        public Nullable<int> UserArea_TotalMonthsManagement { get; set; }
        public Nullable<int> UserArea_HighestManagementScore { get; set; }
        public string UserArea_ManagementSummary { get; set; }
        public string UserArea_CurrentManagementLevel { get; set; }
        public string UserArea_PersonalInformation_DateOfBirth { get; set; }
        public string UserArea_PersonalInformation_Nationality { get; set; }
        public string UserArea_PersonalInformation_Gender { get; set; }
        public string UserArea_PersonalInformation_MaritalStatus { get; set; }
        public string UserArea_PersonalInformation_DrivingLicense { get; set; }
        public string UserArea_PersonalInformation_CurrentLocation { get; set; }
        public string UserArea_PersonalInformation_PreferredLocation { get; set; }
        public string UserArea_PersonalInformation_WillingToRelocate { get; set; }
        public string UserArea_PersonalInformation_FathersName { get; set; }
        public string UserArea_PersonalInformation_MothersMaidenName { get; set; }
        public string UserArea_PersonalInformation_VisaStatus { get; set; }
        public string UserArea_PersonalInformation_PassportNumber { get; set; }
        public Nullable<decimal> UserArea_PersonalInformation_CurrentSalary { get; set; }
        public string UserArea_PersonalInformation_CurrentSalary_CurrencyCode { get; set; }
        public Nullable<decimal> UserArea_PersonalInformation_RequiredSalary { get; set; }
        public string UserArea_PersonalInformation_RequiredSalary_CurrencyCode { get; set; }
        public string UserArea_JobType { get; set; }
        public string UserArea_ExperienceSummary { get; set; }
        public string UserArea_ResumeDirectory { get; set; }
        public string UserArea_ResumeFilename { get; set; }
        public string UserArea_HrXmlResume { get; set; }
        public string UserArea_HtmlResume { get; set; }
        public byte[] UserArea_OriginalResume { get; set; }
        public Nullable<System.DateTime> UserArea_ParseDate { get; set; }
        public string UserArea_ParserVersion { get; set; }
        public string UserArea_ConverterVersion { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> createdBy { get; set; }
        public string branchId { get; set; }
        public string ClientResume { get; set; }
        public string Parsed_Filepath { get; set; }
    
        public virtual ICollection<candidateAchivement_Parsed> candidateAchivement_Parsed { get; set; }
        public virtual ICollection<candidateAddress_Parsed> candidateAddress_Parsed { get; set; }
        public virtual ICollection<candidateCompetency_Parsed> candidateCompetency_Parsed { get; set; }
        public virtual ICollection<candidateEmploymentHistroy_Parsed> candidateEmploymentHistroy_Parsed { get; set; }
        public virtual ICollection<candidateReference_Parsed> candidateReference_Parsed { get; set; }
        public virtual ICollection<candidateSchool_Parsed> candidateSchool_Parsed { get; set; }
    }
}
