//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialization
    {
        public long SpecializationID { get; set; }
        public string Specializations { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string Type { get; set; }
        public string AREA { get; set; }
        public Nullable<decimal> Experience { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> resumeId { get; set; }
        public Nullable<int> temp_userId { get; set; }
        public Nullable<System.DateTime> DateRecieved { get; set; }
        public string Results { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
