//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RadiusSearch_ApplicantID
    {
        public int RDSearchID { get; set; }
        public string UserID { get; set; }
        public string ApplicantSearchId { get; set; }
    }
}
