//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Items
    {
        public int ItemID { get; set; }
        public Nullable<int> ItemTypeID { get; set; }
        public Nullable<int> MeasureID { get; set; }
        public Nullable<int> ItemLocID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public Nullable<int> PrimaryVendorID { get; set; }
        public Nullable<int> AlternateVendorID { get; set; }
        public string AccountNO { get; set; }
        public Nullable<decimal> RateperUnit { get; set; }
        public Nullable<decimal> Saleprice { get; set; }
        public Nullable<decimal> MinimumQty { get; set; }
        public Nullable<decimal> ReorderQty { get; set; }
        public Nullable<decimal> QtyonHand { get; set; }
        public string ItemLocation { get; set; }
        public string ItemUnits { get; set; }
        public string Warranty { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string updatedby { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> NonStock { get; set; }
        public Nullable<decimal> QtyCommitted { get; set; }
        public Nullable<decimal> QtyOnOrder { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
    }
}
