//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AssociatePTODetails_Summary
    {
        public decimal PTO_SummaryId { get; set; }
        public Nullable<decimal> PTO_Id { get; set; }
        public Nullable<System.DateTime> PTO_StartDate { get; set; }
        public Nullable<System.DateTime> PTO_EndDate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public Nullable<decimal> Total_Hours { get; set; }
        public Nullable<decimal> PTO_Hours { get; set; }
        public Nullable<decimal> Earned_PTO { get; set; }
        public Nullable<System.DateTime> Earned_PTODate { get; set; }
        public Nullable<decimal> Total_RunningPTO { get; set; }
        public Nullable<decimal> Incomplete_PTO { get; set; }
        public Nullable<System.DateTime> Weekenddate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
