//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Menus
    {
        public int MenuId { get; set; }
        public string MenuDescription { get; set; }
        public string NavigateURL { get; set; }
        public Nullable<int> ParentMenuId { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
    }
}
