//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RateCalculation
    {
        public long ID { get; set; }
        public Nullable<long> JobOrderID { get; set; }
        public Nullable<long> PlacementID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string PayRateCode { get; set; }
        public Nullable<decimal> PayRate { get; set; }
        public Nullable<decimal> PayRateMultiplier { get; set; }
        public Nullable<decimal> BillRateMultiplier { get; set; }
        public Nullable<decimal> BillRate { get; set; }
    }
}
