//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FormDetails
    {
        public decimal form_ColumnId { get; set; }
        public decimal form_Id { get; set; }
        public string form_ColumnFieldText { get; set; }
        public string form_ColumnFieldValue { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public Nullable<bool> AlwaysShow { get; set; }
        public string form_NewFieldText { get; set; }
    }
}
