//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Candidate_ModifiedLog
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public decimal UserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate_From { get; set; }
        public Nullable<System.DateTime> ModifiedDate_Changed { get; set; }
        public string ModifiedBy { get; set; }
        public decimal HistoryID { get; set; }
        public string HistoryType { get; set; }
        public string Detail { get; set; }
    }
}
