//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ApptrinoSettings
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> Accounting_Status { get; set; }
        public string Timesheet_Type { get; set; }
        public Nullable<bool> PTO_Status { get; set; }
        public Nullable<int> PTO_TotalDays { get; set; }
        public string PTO_TotalHours { get; set; }
        public string PTO_DayGap { get; set; }
        public string PTO_Given { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> Grid_NoOfRecords { get; set; }
        public Nullable<bool> Traverse_Status { get; set; }
        public Nullable<bool> I9 { get; set; }
        public Nullable<bool> W4 { get; set; }
        public Nullable<bool> Form_Status { get; set; }
        public Nullable<bool> LumpSumTimesheet { get; set; }
        public Nullable<bool> Security { get; set; }
        public Nullable<bool> ValidateSalutation { get; set; }
        public Nullable<bool> Validate_PO { get; set; }
        public Nullable<bool> ADP_Status { get; set; }
        public Nullable<bool> Bondable_Status { get; set; }
        public Nullable<bool> CustomReports { get; set; }
        public Nullable<bool> ELearning { get; set; }
        public Nullable<bool> PTO { get; set; }
    }
}
