//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AssociateList
    {
        public int ID { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> branchId { get; set; }
        public string stateCode { get; set; }
        public string fullName { get; set; }
        public string phone { get; set; }
        public Nullable<int> userId { get; set; }
        public string gender { get; set; }
        public string mobile { get; set; }
        public string uniqueDifferentiators { get; set; }
        public string workphone { get; set; }
        public string location { get; set; }
        public string email { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public string type { get; set; }
        public string assoType { get; set; }
        public string office { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CellNumber { get; set; }
        public string Address { get; set; }
        public string postalCode { get; set; }
        public string Zip_Postal { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string cellno { get; set; }
        public string imageStatus { get; set; }
        public string RecruiterNames { get; set; }
        public string yearOfExperience { get; set; }
        public string employeenumber { get; set; }
        public string statename { get; set; }
        public string employmentType { get; set; }
        public string shift { get; set; }
        public string Bilingual { get; set; }
        public string transportation { get; set; }
        public string pee { get; set; }
        public string SeachIndex { get; set; }
    }
}
