//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_IMMUNIZATIONS
    {
        public long ImmuinizationID { get; set; }
        public string ImmuinizationName { get; set; }
        public Nullable<System.DateTime> DateRecieved { get; set; }
        public string Reults { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ResumeID { get; set; }
        public Nullable<long> Temp_UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
