//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Invoice
    {
        public int InvoiceID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> TermsID { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<int> Posted { get; set; }
        public Nullable<bool> IsDrafted { get; set; }
        public string Memo { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsCreditMemo { get; set; }
        public Nullable<bool> isPaid { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<decimal> LateFee { get; set; }
        public string InvoiceType { get; set; }
        public string OrderNo { get; set; }
        public string JobLocation { get; set; }
        public string JobPhone { get; set; }
        public Nullable<System.DateTime> invCretaedDate { get; set; }
        public Nullable<decimal> MiscellaneousAmount { get; set; }
        public Nullable<decimal> LaborAmount { get; set; }
        public Nullable<decimal> MaterialAmount { get; set; }
        public string SoldTo { get; set; }
        public Nullable<int> CreateByUserID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<decimal> EquipmentAmount { get; set; }
        public string Companyname { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> EstInvoiceID { get; set; }
        public string EstInvoiceNo { get; set; }
    }
}
