//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomFields_Value
    {
        public long FieldID { get; set; }
        public int CompanyID { get; set; }
        public string ProgramType { get; set; }
        public long ProgramRecID { get; set; }
        public string FieldValue { get; set; }
    }
}
