//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ApplicantHolidays
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int LeaveCodeId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string LeaveReason { get; set; }
        public string Status { get; set; }
        public int AssignmentId { get; set; }
        public int SupervisorUserId { get; set; }
        public string SupervisorUserComment { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
