//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPosition
    {
        public long positionID { get; set; }
        public string positionDesc { get; set; }
        public Nullable<bool> ynDelete { get; set; }
        public Nullable<int> BranchID { get; set; }
    }
}
