//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_paypolicy
    {
        public int policyid { get; set; }
        public string pcode { get; set; }
        public string pname { get; set; }
        public string ptype { get; set; }
        public string ot_hrs { get; set; }
        public string dt_hrs { get; set; }
        public string sat { get; set; }
        public string sun { get; set; }
        public Nullable<decimal> sat_amt { get; set; }
        public Nullable<decimal> sun_amt { get; set; }
        public string status { get; set; }
        public Nullable<bool> IsWeekendRules { get; set; }
        public Nullable<decimal> BillRateOT { get; set; }
        public Nullable<decimal> BillRateDT { get; set; }
        public Nullable<decimal> PayRateOT { get; set; }
        public Nullable<decimal> PayRateDT { get; set; }
    }
}
