//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_tbl_Contact
    {
        public int ContactId { get; set; }
        public string Initial { get; set; }
        public string fname { get; set; }
        public string phone { get; set; }
        public string Fax { get; set; }
        public string email { get; set; }
        public string title { get; set; }
        public string Source { get; set; }
        public string mobile { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string creator { get; set; }
        public string modifiedBy { get; set; }
        public int AccountId { get; set; }
        public string homephone { get; set; }
        public string otherPhone { get; set; }
        public string AsstPhone { get; set; }
        public string Assistant { get; set; }
        public string EmailOptOut { get; set; }
        public string description { get; set; }
        public string ReportTo { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string department { get; set; }
        public string mailingstreet { get; set; }
        public string otherstreet { get; set; }
        public string mailingcity { get; set; }
        public string othercity { get; set; }
        public string mailingstate { get; set; }
        public string otherstate { get; set; }
        public string mailingzip { get; set; }
        public string otherzip { get; set; }
        public string mailingcountry { get; set; }
        public string othercountry { get; set; }
        public Nullable<bool> reportingManager { get; set; }
        public string suspect_prospect { get; set; }
        public string salesMgr1 { get; set; }
        public string salesMgr2 { get; set; }
        public string contact_office { get; set; }
        public string phoneExt { get; set; }
        public string mailingAddress { get; set; }
        public string billingAddress { get; set; }
        public Nullable<bool> isCorporate { get; set; }
        public string ContactIdEditable { get; set; }
    }
}
