//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_tbl_Account
    {
        public int AccountId { get; set; }
        public string Account_Name { get; set; }
        public string Parent_Account { get; set; }
        public string Phone { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public string Account_type { get; set; }
        public string Account_Industries { get; set; }
        public string Description { get; set; }
        public string accountSite { get; set; }
        public string acountNumber { get; set; }
        public string annualRevenue { get; set; }
        public string rating { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string modifiedBy { get; set; }
        public string trickerSymbol { get; set; }
        public string wonership { get; set; }
        public string employees { get; set; }
        public string sicCode { get; set; }
        public string accountOwner { get; set; }
        public string billingstreet { get; set; }
        public string shippingstreet { get; set; }
        public string billingcity { get; set; }
        public string shippingcity { get; set; }
        public string billingstate { get; set; }
        public string shippingstate { get; set; }
        public string billingzip { get; set; }
        public string shippingzip { get; set; }
        public string billingcountry { get; set; }
        public string shippingcountry { get; set; }
        public string naicscode { get; set; }
        public string suspect_prospect { get; set; }
        public string salesMgr1 { get; set; }
        public string salesMgr2 { get; set; }
        public string account_office { get; set; }
        public string phoneExt { get; set; }
        public string mailingAddress { get; set; }
        public string billingAddress { get; set; }
        public Nullable<bool> isCorporate { get; set; }
        public string accountingCustomerId { get; set; }
        public Nullable<bool> roundToquarter { get; set; }
        public Nullable<decimal> markUp { get; set; }
        public string AccountIdEditable { get; set; }
        public string ReferredBy { get; set; }
        public string shippingstateName { get; set; }
    }
}
