//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet_summary
    {
        public long tsid { get; set; }
        public string UserID { get; set; }
        public string AssociateName { get; set; }
        public string assignmentId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> REG_Hrs { get; set; }
        public Nullable<decimal> OT_Hrs { get; set; }
        public Nullable<decimal> DT_Hrs { get; set; }
        public Nullable<decimal> Total_Hrs { get; set; }
        public string status { get; set; }
    }
}
