//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public string BadgeID { get; set; }
        public string OtherID { get; set; }
        public int Counter { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<double> LunchMinutes { get; set; }
        public string PunchType { get; set; }
        public Nullable<int> PlacementID { get; set; }
        public Nullable<double> RegHours { get; set; }
        public Nullable<double> OTHours { get; set; }
        public Nullable<double> DTHours { get; set; }
        public Nullable<double> TotalTime { get; set; }
        public string PayType { get; set; }
        public string PayTypeDescription { get; set; }
        public Nullable<bool> AccrueOT { get; set; }
        public Nullable<int> TimeType { get; set; }
        public string StartLocationNo { get; set; }
        public Nullable<byte> StartLocationType { get; set; }
        public string StartLocationName { get; set; }
        public string EndLocationNo { get; set; }
        public Nullable<byte> EndLocationType { get; set; }
        public string EndLocationName { get; set; }
        public string CompanyCode { get; set; }
        public bool isUpdated { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string PunchAddress { get; set; }
    }
}
