//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class US100AttendanceLog
    {
        public int Counter { get; set; }
        public string DeviceNumber { get; set; }
        public string IPAdderess { get; set; }
        public string PunchType { get; set; }
        public string BadgeID { get; set; }
        public string PlacementID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string CompanyCode { get; set; }
        public bool IsUploaded { get; set; }
        public bool IsSms { get; set; }
        public bool IsEmail { get; set; }
        public Nullable<int> WorkCode { get; set; }
        public Nullable<int> Reserved { get; set; }
    }
}
