//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class US100Devices
    {
        public int ID { get; set; }
        public string Status { get; set; }
        public string DeviceName { get; set; }
        public string DeviceNumber { get; set; }
        public string DeviceIP { get; set; }
        public string Location { get; set; }
        public bool IPConnection { get; set; }
        public bool USBConnection { get; set; }
        public bool RSCOMConnection { get; set; }
        public string IPPort { get; set; }
        public string MachineSN { get; set; }
        public string BaudRate { get; set; }
        public string RSPort { get; set; }
        public string CompanyCode { get; set; }
        public string AccountID { get; set; }
    }
}
