//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class US100IFACEPrints
    {
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> Privilege { get; set; }
        public int FaceIndex { get; set; }
        public byte[] tmpData { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<bool> Ennabled { get; set; }
        public string CompanyCode { get; set; }
        public string DeviceName { get; set; }
    }
}
