//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int Userid { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    }
}
