//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccessModule
    {
        public long ID { get; set; }
        public long Userid { get; set; }
        public bool DashBoard { get; set; }
        public bool Scheduler { get; set; }
        public bool CRM { get; set; }
        public bool ROI { get; set; }
        public bool Applicants { get; set; }
        public bool Jobs { get; set; }
        public bool Timesheet { get; set; }
        public bool Mail { get; set; }
        public bool Reports { get; set; }
        public bool Accounting { get; set; }
        public bool Setup { get; set; }
    }
}
