//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_stage
    {
        public decimal userId { get; set; }
        public string loginId { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string middleInitial { get; set; }
        public string lastName { get; set; }
        public string phone { get; set; }
        public Nullable<decimal> phoneExt { get; set; }
        public Nullable<decimal> Fax { get; set; }
        public string email { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postalCode { get; set; }
        public Nullable<decimal> postalCodeExt { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public string stateCode { get; set; }
        public Nullable<decimal> roleId { get; set; }
        public string status { get; set; }
        public string modifiedBy { get; set; }
        public string ssnNo { get; set; }
        public Nullable<decimal> mobile { get; set; }
        public Nullable<decimal> workPhone { get; set; }
        public Nullable<decimal> emergencyNumber { get; set; }
        public string contactPerson { get; set; }
        public string resume { get; set; }
        public string officeSentTo { get; set; }
        public string employmentType { get; set; }
        public string shift { get; set; }
        public string salary { get; set; }
        public string availability { get; set; }
        public string wToHeard { get; set; }
        public string txtwToHeard { get; set; }
        public Nullable<bool> isFelony { get; set; }
        public string felonyDesc { get; set; }
        public Nullable<bool> isWorked { get; set; }
        public string sourceCode { get; set; }
        public string federalId { get; set; }
        public Nullable<decimal> resaleTax { get; set; }
        public Nullable<bool> willReceiveMail { get; set; }
        public string salaryType { get; set; }
        public string branchName { get; set; }
        public string Bilingual { get; set; }
        public string Transportation { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Salutation { get; set; }
        public string Relocate1 { get; set; }
        public string Relocate2 { get; set; }
        public string Travel { get; set; }
        public Nullable<bool> Employment_Locally { get; set; }
        public Nullable<bool> Employment_CrossCountry { get; set; }
        public Nullable<bool> Employment_Overseas { get; set; }
        public Nullable<bool> isAllowSMS { get; set; }
        public string ProviderId { get; set; }
        public string pee { get; set; }
        public string gender { get; set; }
        public string Bond { get; set; }
        public Nullable<bool> isEligibleForEmploymentUSA { get; set; }
        public Nullable<bool> isConvictedOfFelonyDeferredAdjudication { get; set; }
        public string ConvictedOfFelonyDeferredAdjudicationExplain { get; set; }
        public string LimitationsThatRequireSpecialAccommodations { get; set; }
        public string EmergencyContactRelationship { get; set; }
        public string ReferralemployeeName { get; set; }
        public Nullable<bool> haveWorkedTempAgency { get; set; }
        public string tempAgencyWhenFrom { get; set; }
        public string tempAgencyWhenTo { get; set; }
        public string tempAgencyName { get; set; }
        public string isWorkedDepartment { get; set; }
        public string isWorkedDateFrom { get; set; }
        public string isWorkedDateTo { get; set; }
        public string isWorkedReasonOfLeaving { get; set; }
        public string areaOfInterest { get; set; }
        public Nullable<bool> isEligibleAge { get; set; }
        public string WorkHour { get; set; }
        public string workStartDate { get; set; }
        public string LiftingAbility { get; set; }
        public string CompanySentServices { get; set; }
        public Nullable<bool> isTakeDrugScreen { get; set; }
        public string PlacementReq { get; set; }
        public string PlacementType { get; set; }
        public string NurseType { get; set; }
        public string PlacementHour { get; set; }
        public string AdditionalSkill { get; set; }
        public string Position { get; set; }
        public Nullable<bool> IsLived5Years { get; set; }
        public string ProfilePicture { get; set; }
        public string EmploymentTypes { get; set; }
        public string Location { get; set; }
    }
}
