//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venture
    {
        public long VentureId { get; set; }
        public string VentureName { get; set; }
        public string LeadMentor { get; set; }
        public Nullable<int> VmsStatusId { get; set; }
        public string PrimaryContact { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryContact { get; set; }
        public string SecondaryEmail { get; set; }
        public string DropBox { get; set; }
        public string Description { get; set; }
        public string DropBoxFolder { get; set; }
        public string PublicDesc { get; set; }
        public string ContactInfo { get; set; }
        public string VmsMailList { get; set; }
        public string SignUpReturned { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Cellular { get; set; }
        public string WebSite { get; set; }
        public string MITLink { get; set; }
        public Nullable<bool> StudentIdeaBasedOnResearch { get; set; }
        public Nullable<bool> ResearchIdeaDisclosedToTLO { get; set; }
        public Nullable<bool> LegalEntityAtEnrollment { get; set; }
        public string RefferedBy { get; set; }
        public string FirstMentorMeeting { get; set; }
        public string Comments { get; set; }
        public string IntakeNotes { get; set; }
        public string IntakeNoteSummary { get; set; }
        public string SecondContact { get; set; }
        public Nullable<bool> Introduced { get; set; }
        public string SeachIndex { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBY { get; set; }
        public Nullable<int> ModifiedBY { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
