//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentureDetail
    {
        public long VentureDetailsId { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string IndustryCategoryName { get; set; }
        public string CategoryOthers { get; set; }
        public string PrimaryPhoneNo { get; set; }
        public string PrimaryRoleInVenture { get; set; }
        public string PrimaryColaborationAffiliation { get; set; }
        public string SecondaryPhoneNo { get; set; }
        public string SecondaryRoleInVenture { get; set; }
        public string ScondaryColaborationAffiliation { get; set; }
        public string Advertisement { get; set; }
        public string WouldLikeToElaborateSpecifics { get; set; }
        public string WhatDoYouDo { get; set; }
        public string WhatIsTheProblem { get; set; }
        public string WhoHasIt { get; set; }
        public string HowWillUSolveTheProblem { get; set; }
        public string HowWillUMakeMoney { get; set; }
        public string WhtIsTheSecretSauce { get; set; }
        public string IsThereIP { get; set; }
        public string WhatIsYourCurrentStatus { get; set; }
        public string WhatTypeOfVMSHelpStartUpNeeds { get; set; }
        public Nullable<long> VentureId { get; set; }
    }
}
