//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class workOrderDocument
    {
        public decimal documentId { get; set; }
        public string documentType { get; set; }
        public string fileName { get; set; }
        public string sessionId { get; set; }
        public Nullable<decimal> workOrderId { get; set; }
        public string status { get; set; }
        public string assignmentId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
