//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder_History
    {
        public decimal Id { get; set; }
        public Nullable<decimal> requisitionId { get; set; }
        public string YrExp { get; set; }
        public string JobType { get; set; }
        public string MinEducation { get; set; }
        public string SkillLevel { get; set; }
        public string Location { get; set; }
        public string PosDescription { get; set; }
        public string payRate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string modifiedBy { get; set; }
    }
}
