//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHub.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class zipCode
    {
        public decimal Id { get; set; }
        public Nullable<double> ZipCode1 { get; set; }
        public string City { get; set; }
        public string StateCode { get; set; }
    }
}
